rel: prep beta release 0.1.0b0
honeycombio/honeycomb-opentelemetry-python pull request #112
Opened 2023-03-29 20:08 UTC by JamieDanielson

## Which problem is this PR solving?

- lack of a published beta package

## Short description of the changes

- update version in `pyproject.toml` to 0.1.0b0
- add notes in `CHANGELOG.md` for beta release
- small cleanup throughout (typos, formatting, etc to clear up squigglies from my editor)

2023-03-29 21:08 UTC, robbkidd reviewed
A question about the next version number …

2023-03-29 21:08 UTC, robbkidd commented on CHANGELOG.md
> +- maint: drop poetry locks from example apps (#111) | [@JamieDanielson](https://github.com/JamieDanielson)
Ride the Lightning!

![](https://media.tenor.com/PYFq3xQUeOgAAAAC/hangover-alan.gif)

2023-03-29 21:08 UTC, robbkidd commented on pyproject.toml
> +version = "0.1.0b0"
🤔   I was expecting maybe `0.1.2b0` or `0.2.0b0`. Why go downwards with the patch version?

2023-03-29 21:48 UTC, robbkidd requested changes
Here's a proposed patch bump from 0.1.1a3 to 0.1.2b0 coming in as suggested edits that can be accepted in one commit. If accepted, we can update the PR title and ignore the branch name.

2023-03-29 21:48 UTC, robbkidd commented on CHANGELOG.md
> +## [0.1.0b0] - 2023-03-29
```suggestion
## [0.1.2b0] - 2023-03-29
```

2023-03-29 21:48 UTC, robbkidd commented on pyproject.toml
> +version = "0.1.0b0"
```suggestion
version = "0.1.2b0"
```

2023-03-30 10:29 UTC, MikeGoldsmith approved these changes
🎉

2023-03-30 10:40 UTC, merged